/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.mysql.jdbc.PreparedStatement;
import components.DocumentSizeFilter;
import dbconnector.DBconnector;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.MaskFormatter;
import projetozikavirus.TelaPrincipal;
import validadores.ValidaCPF;
import validadores.ValidaCampos;
/**
 *
 * @author Fabio
 */
public class NovoPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoPaciente
     */
    private static boolean podeProsseguir = false;
    private String nrCPF = "";
    private String nrCaso = "";
    private ResultSet resultSet = null;
    private Statement statement = null;
    private Connection connection = null;
    private PreparedStatement preparedStatement = null;
    private DefaultStyledDocument doc;
    
    ValidaCampos validaCampos = new ValidaCampos();
    DBconnector conexao = new DBconnector();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy");
    JDesktopPane desktop = super.getDesktopPane();
    BuscarPaciente buscarPaciente = new BuscarPaciente();
    
    public NovoPaciente() throws ParseException {
        initComponents();
        
        MaskFormatter maskNrCaso = new MaskFormatter("###");
        maskNrCaso.install(txtNrCaso);
        
        MaskFormatter maskCPF = new MaskFormatter("###.###.###-##");
        maskCPF.install(txtCPF);
        
        contPalavras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbAmostra1 = new javax.swing.JComboBox<>();
        cmbAmostra2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbAmostra3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbAmostra4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbFinalMae = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbFinalRN = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtSoro = new javax.swing.JTextField();
        txtPlasma = new javax.swing.JTextField();
        txtSaliva = new javax.swing.JTextField();
        txtSemen = new javax.swing.JTextField();
        txtLeiteMaterno = new javax.swing.JTextField();
        txtUrina = new javax.swing.JTextField();
        txtLiquor = new javax.swing.JTextField();
        txtPlacenta = new javax.swing.JTextField();
        txtCordaoUmbilical = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblContPalavras = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaObs = new javax.swing.JTextPane();
        lblNrCaso = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNrCaso = new javax.swing.JFormattedTextField();
        dtEntrada = new org.jdesktop.swingx.JXDatePicker();
        dtColeta1 = new org.jdesktop.swingx.JXDatePicker();
        dtColeta2 = new org.jdesktop.swingx.JXDatePicker();
        dtColeta3 = new org.jdesktop.swingx.JXDatePicker();
        dtColeta4 = new org.jdesktop.swingx.JXDatePicker();
        dtColeta5 = new org.jdesktop.swingx.JXDatePicker();
        lblDtEntrada = new javax.swing.JLabel();
        lblDtCol1 = new javax.swing.JLabel();
        lblDtCol2 = new javax.swing.JLabel();
        lblDtCol3 = new javax.swing.JLabel();
        lblDtCol4 = new javax.swing.JLabel();
        lblDtCol5 = new javax.swing.JLabel();

        jLabel17.setText("jLabel17");

        setClosable(true);
        setTitle("Novo Paciente");
        setPreferredSize(new java.awt.Dimension(780, 560));

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Numero do Caso:");

        jLabel4.setText("Data da 1ª Coleta:");

        jLabel5.setText("Data da 2ª Coleta:");

        jLabel6.setText("Data da 3ª Coleta:");

        jLabel7.setText("Data da 4ª Coleta:");

        jLabel8.setText("Data da 5ª Coleta:");

        txtNomeCompleto.setText("Informe o Nome Completo");
        txtNomeCompleto.setNextFocusableComponent(txtCPF);
        txtNomeCompleto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCompletoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeCompletoFocusLost(evt);
            }
        });
        txtNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompletoActionPerformed(evt);
            }
        });

        txtCPF.setNextFocusableComponent(dtColeta1);
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });

        jLabel9.setText("Data da Entrada: ");

        btnCriar.setText("Criar Paciente");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        jLabel10.setText("1ª Amostra:");

        cmbAmostra1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbAmostra1.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbAmostra1.setName(""); // NOI18N
        cmbAmostra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmostra1ActionPerformed(evt);
            }
        });

        cmbAmostra2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbAmostra2.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbAmostra2.setName(""); // NOI18N
        cmbAmostra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmostra2ActionPerformed(evt);
            }
        });

        jLabel11.setText("2ª Amostra:");

        cmbAmostra3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbAmostra3.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbAmostra3.setName(""); // NOI18N
        cmbAmostra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmostra3ActionPerformed(evt);
            }
        });

        jLabel12.setText("3ª Amostra:");

        cmbAmostra4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbAmostra4.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbAmostra4.setName(""); // NOI18N
        cmbAmostra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmostra4ActionPerformed(evt);
            }
        });

        jLabel13.setText("4ª Amostra:");

        cmbFinalMae.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbFinalMae.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbFinalMae.setName(""); // NOI18N
        cmbFinalMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFinalMaeActionPerformed(evt);
            }
        });

        jLabel14.setText("Final da Mãe:");

        cmbFinalRN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbFinalRN.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbFinalRN.setName(""); // NOI18N
        cmbFinalRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFinalRNActionPerformed(evt);
            }
        });

        jLabel15.setText("Final do RN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cmbAmostra1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cmbAmostra2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cmbAmostra3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(cmbAmostra4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cmbFinalMae, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cmbFinalRN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFinalRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFinalMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAmostra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAmostra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAmostra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAmostra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resultados", jPanel1);

        jLabel18.setText("Informar a quantidade total das seguites amostras:");

        jLabel19.setText("Soro:");

        jLabel20.setText("Plasma:");

        jLabel21.setText("Saliva:");

        jLabel22.setText("Urina:");

        jLabel23.setText("Sêmen:");

        jLabel24.setText("Leite Materno:");

        jLabel25.setText("Liquor:");

        jLabel26.setText("Placenta:");

        jLabel27.setText("Cordão Umbilical:");

        txtSoro.setText("0");
        txtSoro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSoroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoroFocusLost(evt);
            }
        });
        txtSoro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSoroMouseExited(evt);
            }
        });

        txtPlasma.setText("0");
        txtPlasma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlasmaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlasmaFocusLost(evt);
            }
        });

        txtSaliva.setText("0");
        txtSaliva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSalivaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalivaFocusLost(evt);
            }
        });

        txtSemen.setText("0");
        txtSemen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSemenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSemenFocusLost(evt);
            }
        });

        txtLeiteMaterno.setText("0");
        txtLeiteMaterno.setToolTipText("");
        txtLeiteMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLeiteMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLeiteMaternoFocusLost(evt);
            }
        });

        txtUrina.setText("0");
        txtUrina.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUrinaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUrinaFocusLost(evt);
            }
        });

        txtLiquor.setText("0");
        txtLiquor.setToolTipText("");
        txtLiquor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLiquorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLiquorFocusLost(evt);
            }
        });

        txtPlacenta.setText("0");
        txtPlacenta.setToolTipText("");
        txtPlacenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlacentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacentaFocusLost(evt);
            }
        });

        txtCordaoUmbilical.setText("0");
        txtCordaoUmbilical.setToolTipText("");
        txtCordaoUmbilical.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCordaoUmbilicalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCordaoUmbilicalFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtPlasma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50))
                                .addComponent(txtSoro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSaliva, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLeiteMaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUrina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCordaoUmbilical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlacenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLiquor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtLiquor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCordaoUmbilical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22)
                            .addComponent(txtSoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUrina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)
                            .addComponent(txtPlasma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24)
                            .addComponent(txtSaliva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLeiteMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Amostras", jPanel2);

        jScrollPane2.setViewportView(txtAreaObs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 591, Short.MAX_VALUE)
                .addComponent(lblContPalavras, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblContPalavras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Obeservações", jPanel3);

        lblNrCaso.setText("Nr Caso");

        lblCPF.setText("CPF");

        lblNome.setText("Nome");

        jLabel16.setText("\\16");

        txtNrCaso.setNextFocusableComponent(dtEntrada);
        txtNrCaso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNrCasoFocusLost(evt);
            }
        });

        dtEntrada.setNextFocusableComponent(txtNomeCompleto);

        lblDtEntrada.setText("entrada");

        lblDtCol1.setText("col1");

        lblDtCol2.setText("col2");

        lblDtCol3.setText("col3");

        lblDtCol4.setText("col4");

        lblDtCol5.setText("col5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCriar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtColeta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDtCol5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtColeta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDtCol4)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNrCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addGap(32, 32, 32)
                                .addComponent(lblNrCaso)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblDtEntrada)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCPF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dtColeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDtCol1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dtColeta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDtCol2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dtColeta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDtCol3))))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(txtNrCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNrCaso)
                    .addComponent(lblDtEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtColeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblDtCol1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtColeta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblDtCol2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtColeta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblDtCol3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dtColeta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtCol4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dtColeta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtCol5))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCriar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void contPalavras(){
        doc = new DefaultStyledDocument();
        doc.setDocumentFilter(new DocumentSizeFilter(500));
            doc.addDocumentListener(new DocumentListener(){
                @Override
                public void changedUpdate(DocumentEvent e) { updateCount();}
                @Override
                public void insertUpdate(DocumentEvent e) { updateCount();}
                @Override
                public void removeUpdate(DocumentEvent e) { updateCount();}          
            });
            txtAreaObs.setDocument(doc);
            updateCount();
    }
    private void updateCount() {
           lblContPalavras.setText(((500) -doc.getLength()) + " letras restando!");                      
    }
    
    public void datePickerSetup(){
        if (dtEntrada.getDate() == null){
            lblDtEntrada.setText("");
        }else{
            lblDtEntrada.setText(formatter.format(dtEntrada.getDate()));
        }
        if (dtColeta1.getDate() == null){
            lblDtCol1.setText("");
        }else{
            lblDtCol1.setText(formatter.format(dtColeta1.getDate()));
        }
        if (dtColeta2.getDate() == null){
            lblDtCol2.setText("");
        }else{
            lblDtCol2.setText(formatter.format(dtColeta2.getDate()));
        }
        if (dtColeta3.getDate() == null){
            lblDtCol3.setText("");
        }else{
            lblDtCol3.setText(formatter.format(dtColeta3.getDate()));
        }
        if (dtColeta4.getDate() == null){
            lblDtCol4.setText("");
        }else{
            lblDtCol4.setText(formatter.format(dtColeta4.getDate()));
        }
        if (dtColeta5.getDate() == null){
            lblDtCol5.setText("");
        }else{
            lblDtCol5.setText(formatter.format(dtColeta5.getDate()));
        }
    }
    
    private void apagarCampos(){
        txtNrCaso.setText("");
        dtEntrada.setDate(null);
        txtNomeCompleto.setText("");
        txtCPF.setText("");
        dtColeta1.setDate(null);
        dtColeta2.setDate(null);
        dtColeta3.setDate(null);
        dtColeta4.setDate(null);
        dtColeta5.setDate(null);
        cmbAmostra1.setSelectedIndex(0);
        cmbAmostra2.setSelectedIndex(0);
        cmbAmostra3.setSelectedIndex(0);
        cmbAmostra4.setSelectedIndex(0);
        cmbFinalMae.setSelectedIndex(0);
        cmbFinalRN.setSelectedIndex(0);
        txtCordaoUmbilical.setText("0");
        txtLeiteMaterno.setText("0");
        txtLiquor.setText("0");
        txtPlacenta.setText("0");
        txtPlasma.setText("0");
        txtSaliva.setText("0");
        txtSemen.setText("0");
        txtSoro.setText("0");
        txtUrina.setText("0");
        txtAreaObs.setText("0");
    }
    
    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        datePickerSetup();

// implementar se for obrigatorio todos os pacientes de terem CPF e retirar codigo do txtCPFFocusLost

//        if (!ValidaCPF.isCPF(lblCPF.getText())) {
//            JOptionPane.showMessageDialog(rootPane, "CPF inválido!");
//            podeProsseguir = false;
//        }else{ podeProsseguir = true; }
        if (validaCampos.validaNomeCompleto(lblNome.getText())) {
            JOptionPane.showMessageDialog(rootPane, "O campo NOME COMPLETO está em branco!");
            podeProsseguir = false; 
        }else{ podeProsseguir = true; }
        try{
            if (validaCampos.validaCampoNrCaso(Integer.parseInt(txtNrCaso.getText()))) {
                JOptionPane.showMessageDialog(rootPane, "O campo NUMERO DO CASO está em inválido!");
                podeProsseguir = false;
            }else{ podeProsseguir = true; }
        }catch (NumberFormatException nFE){
            JOptionPane.showMessageDialog(rootPane, "O campo NUMERO DO CASO está no formato inválido! \n"
                    + "Por favor digite no seguinte formato com tres numeros, por exemplo: 003");
            podeProsseguir = false;
        }
                               
        if (podeProsseguir) {  
            
                try {
                    
                    conexao.conexao();
//                    System.out.println("-------- MySQL JDBC Connection Testing ------------");
//
//                    try {
//                            Class.forName("com.mysql.jdbc.Driver");
//                    } catch (ClassNotFoundException e) {
//                            System.out.println("Where is your MySQL JDBC Driver?");
//                            e.printStackTrace();
//                            return;
//                    }
//
//                    System.out.println("MySQL JDBC Driver Registered!");
//                    Connection connection = null;
//
//                    try {
//                            connection = DriverManager
//                            .getConnection("jdbc:mysql://localhost:3306/projetozikadb","root", "lmi56n");
//
//                    } catch (SQLException e) {
//                            System.out.println("Connection Failed! Check output console");
//                            e.printStackTrace();
//                            return;
//                    }
//
//                    if (connection != null) {
//                            System.out.println("You made it, take control your database now!");
//                    } else {
//                            System.out.println("Failed to make connection!");
//                    }

                             
                    statement = conexao.connection.createStatement();
                    preparedStatement = (PreparedStatement) conexao.connection.prepareStatement("SELECT NomeCompleto, NumeroCaso FROM pacientes WHERE NomeCompleto = '" + txtNomeCompleto.getText()+ "' or NumeroCaso = '"+ txtNrCaso.getText() +"'");                    
                    resultSet = preparedStatement.executeQuery();
                    
                    String nomeCompleto = "";
                    String numeroCaso = "";
                    boolean empty = true;
                    
                    while( resultSet.next() ) {
                        // ResultSet processing here
                        nomeCompleto = resultSet.getString("NomeCompleto");
                        numeroCaso = resultSet.getString("NumeroCaso");
                        System.out.println("Caso: " + numeroCaso + "Nome: " + nomeCompleto);
                        if (nomeCompleto.equals(txtNomeCompleto.getText())) {
                            JOptionPane.showMessageDialog(rootPane, "Paciente: " + txtNomeCompleto.getText() + ", já está cadastrado!");
                        }
                        if (numeroCaso.equals(txtNrCaso.getText())) {
                            JOptionPane.showMessageDialog(rootPane, "Numero Caso: " + txtNrCaso.getText() + ", já está cadastrado!");
                        }
                        
                        empty = false;
                    }

                    if( empty ) {
                        //parte que insere dados do paciente na tabela pacientes
                        preparedStatement = (PreparedStatement) conexao.connection.prepareStatement("INSERT INTO pacientes VALUES(default, ?, ?, ?, ?, ?)");
                        preparedStatement.setString(1, lblNome.getText());
                        preparedStatement.setString(2, lblCPF.getText());
                        preparedStatement.setString(3, lblDtEntrada.getText());
                        preparedStatement.setString(4, txtNrCaso.getText());
                        preparedStatement.setString(5, txtAreaObs.getText());
                        preparedStatement.executeUpdate();
                        
                        //parte que insere os resultados do paciente na tabela resultados
                        preparedStatement = (PreparedStatement) conexao.connection.prepareStatement("INSERT INTO resultados VALUES(default,(SELECT ID_Paciente FROM pacientes WHERE NomeCompleto = '"+ txtNomeCompleto.getText() +"'), ?, ?, ?, ?, ?, ?)");
                        preparedStatement.setString(1, cmbAmostra1.getSelectedItem().toString());
                        preparedStatement.setString(2, cmbAmostra2.getSelectedItem().toString());
                        preparedStatement.setString(3, cmbAmostra3.getSelectedItem().toString());
                        preparedStatement.setString(4, cmbAmostra4.getSelectedItem().toString());
                        preparedStatement.setString(5, cmbFinalMae.getSelectedItem().toString());
                        preparedStatement.setString(6, cmbFinalRN.getSelectedItem().toString());
                        preparedStatement.executeUpdate();
                        
                        //parte que insere os resultados do paciente na tabela resultados
                        preparedStatement = (PreparedStatement) conexao.connection.prepareStatement("INSERT INTO amostras VALUES(default,(SELECT ID_Paciente FROM pacientes WHERE NomeCompleto = '"+ txtNomeCompleto.getText() +"'), ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                        preparedStatement.setString(1, txtSoro.getText());
                        preparedStatement.setString(2, txtPlasma.getText());
                        preparedStatement.setString(3, txtSaliva.getText());
                        preparedStatement.setString(4, txtUrina.getText());
                        preparedStatement.setString(5, txtSemen.getText());
                        preparedStatement.setString(6, txtLiquor.getText());
                        preparedStatement.setString(7, txtLeiteMaterno.getText());
                        preparedStatement.setString(8, txtPlacenta.getText());
                        preparedStatement.setString(9, txtCordaoUmbilical.getText());
                        preparedStatement.executeUpdate();
                        
                        //parte que insere as datas das coletas na tabela coletas
                        preparedStatement = (PreparedStatement) conexao.connection.prepareStatement("INSERT INTO coletas VALUES(default,(SELECT ID_Paciente FROM pacientes WHERE NomeCompleto = '"+ txtNomeCompleto.getText() +"'), ?, ?, ?, ?, ?)");
                        preparedStatement.setString(1, lblDtCol1.getText());
                        preparedStatement.setString(2, lblDtCol2.getText());
                        preparedStatement.setString(3, lblDtCol3.getText());
                        preparedStatement.setString(4, lblDtCol4.getText());
                        preparedStatement.setString(5, lblDtCol5.getText());
                        preparedStatement.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Paciente: " + txtNomeCompleto.getText() + ", cadastrado com sucesso!");
                        apagarCampos();                                                
                        
                        preparedStatement.close();
                    }                    
                    
                    conexao.connection.close();
            }catch (SQLException ex){
                // handle any errors
                System.out.println("SQLException: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("VendorError: " + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_btnCriarActionPerformed


    private void txtNomeCompletoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCompletoFocusGained
        if (txtNomeCompleto.getText().equals("Informe o Nome Completo")) {
            txtNomeCompleto.setText("");
        }
    }//GEN-LAST:event_txtNomeCompletoFocusGained

    private void txtNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompletoActionPerformed

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
        String auxCPF1 = txtCPF.getText();
        String auxCPF2 = auxCPF1.replace(".", "");
        String auxCPF3 = auxCPF2.replace("-", "");
        String nrCPF = auxCPF3.replace(" ", "");
        
        lblCPF.setText(nrCPF);

        if (!nrCPF.equals("")) {
            if (!ValidaCPF.isCPF(lblCPF.getText())) {
                JOptionPane.showMessageDialog(rootPane, "CPF inválido!");
                podeProsseguir = false;
            }
            
        }
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtNomeCompletoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCompletoFocusLost
        lblNome.setText(txtNomeCompleto.getText());
    }//GEN-LAST:event_txtNomeCompletoFocusLost

    private void txtNrCasoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNrCasoFocusLost
        lblNrCaso.setText(txtNrCaso.getText());
    }//GEN-LAST:event_txtNrCasoFocusLost

    private void cmbFinalRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFinalRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFinalRNActionPerformed

    private void cmbFinalMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFinalMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFinalMaeActionPerformed

    private void cmbAmostra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmostra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmostra4ActionPerformed

    private void cmbAmostra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmostra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmostra3ActionPerformed

    private void cmbAmostra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmostra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmostra2ActionPerformed

    private void cmbAmostra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmostra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmostra1ActionPerformed

    private void txtSoroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoroMouseClicked
        
    }//GEN-LAST:event_txtSoroMouseClicked

    private void txtSoroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoroMouseExited
        
    }//GEN-LAST:event_txtSoroMouseExited

    private void txtSoroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoroFocusLost
        for (int i = 0; i < txtSoro.getText().length(); i++) {
            char aux = txtSoro.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtSoro.select(i, i+1);
                txtSoro.replaceSelection("");
            }
        }
        
        if (txtSoro.getText().equals("") || txtSoro.getText().equals(" ")) {
            txtSoro.setText("0");
        }
    }//GEN-LAST:event_txtSoroFocusLost

    private void txtSoroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoroFocusGained
        if (txtSoro.getText().equals("0") || txtSoro.getText().equals(" ")) {
            txtSoro.setText("");
        }
        
    }//GEN-LAST:event_txtSoroFocusGained

    private void txtPlasmaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlasmaFocusLost
        for (int i = 0; i < txtPlasma.getText().length(); i++) {
            char aux = txtPlasma.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtPlasma.select(i, i+1);
                txtPlasma.replaceSelection("");
            }
        }
        
        if (txtPlasma.getText().equals("") || txtPlasma.getText().equals(" ")) {
            txtPlasma.setText("0");
        }
    }//GEN-LAST:event_txtPlasmaFocusLost

    private void txtSalivaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalivaFocusLost
        for (int i = 0; i < txtSaliva.getText().length(); i++) {
            char aux = txtSaliva.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtSaliva.select(i, i+1);
                txtSaliva.replaceSelection("");
            }
        }
        
        if (txtSaliva.getText().equals("") || txtSaliva.getText().equals(" ")) {
            txtSaliva.setText("0");
        }
    }//GEN-LAST:event_txtSalivaFocusLost

    private void txtUrinaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUrinaFocusLost
        for (int i = 0; i < txtUrina.getText().length(); i++) {
            char aux = txtUrina.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtUrina.select(i, i+1);
                txtUrina.replaceSelection("");
            }
        }
        
        if (txtUrina.getText().equals("") || txtUrina.getText().equals(" ")) {
            txtUrina.setText("0");
        }
    }//GEN-LAST:event_txtUrinaFocusLost

    private void txtSemenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemenFocusLost
        for (int i = 0; i < txtSemen.getText().length(); i++) {
            char aux = txtSemen.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtSemen.select(i, i+1);
                txtSemen.replaceSelection("");
            }
        }
        
        if (txtSemen.getText().equals("") || txtSemen.getText().equals(" ")) {
            txtSemen.setText("0");
        }
    }//GEN-LAST:event_txtSemenFocusLost

    private void txtLeiteMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLeiteMaternoFocusLost
        for (int i = 0; i < txtLeiteMaterno.getText().length(); i++) {
            char aux = txtLeiteMaterno.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtLeiteMaterno.select(i, i+1);
                txtLeiteMaterno.replaceSelection("");
            }
        }
        
        if (txtLeiteMaterno.getText().equals("") || txtLeiteMaterno.getText().equals(" ")) {
            txtLeiteMaterno.setText("0");
        }
    }//GEN-LAST:event_txtLeiteMaternoFocusLost

    private void txtLiquorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLiquorFocusLost
        for (int i = 0; i < txtLiquor.getText().length(); i++) {
            char aux = txtLiquor.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtLiquor.select(i, i+1);
                txtLiquor.replaceSelection("");
            }
        }
        
        if (txtLiquor.getText().equals("") || txtLiquor.getText().equals(" ")) {
            txtLiquor.setText("0");
        }
    }//GEN-LAST:event_txtLiquorFocusLost

    private void txtPlacentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacentaFocusLost
        for (int i = 0; i < txtPlacenta.getText().length(); i++) {
            char aux = txtPlacenta.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtPlacenta.select(i, i+1);
                txtPlacenta.replaceSelection("");
            }
        }
        
        if (txtPlacenta.getText().equals("") || txtPlacenta.getText().equals(" ")) {
            txtPlacenta.setText("0");
        }
    }//GEN-LAST:event_txtPlacentaFocusLost

    private void txtCordaoUmbilicalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCordaoUmbilicalFocusLost
       for (int i = 0; i < txtCordaoUmbilical.getText().length(); i++) {
            char aux = txtCordaoUmbilical.getText().charAt(i);
            if (aux == '0' || aux == '1' || aux == '2' || aux == '3' || aux == '4' || aux == '5' || aux == '6' || aux == '7' || aux == '8' || aux == '9') {
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Somente numeros!");
                txtCordaoUmbilical.select(i, i+1);
                txtCordaoUmbilical.replaceSelection("");
            }
        }
        
        if (txtCordaoUmbilical.getText().equals("") || txtCordaoUmbilical.getText().equals(" ")) {
            txtCordaoUmbilical.setText("0");
        }
    }//GEN-LAST:event_txtCordaoUmbilicalFocusLost

    private void txtPlasmaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlasmaFocusGained
        if (txtPlasma.getText().equals("0") || txtPlasma.getText().equals(" ")) {
            txtPlasma.setText("");
        }
    }//GEN-LAST:event_txtPlasmaFocusGained

    private void txtSalivaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalivaFocusGained
        if (txtSaliva.getText().equals("0") || txtSaliva.getText().equals(" ")) {
            txtSaliva.setText("");
        }
    }//GEN-LAST:event_txtSalivaFocusGained

    private void txtUrinaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUrinaFocusGained
        if (txtUrina.getText().equals("0") || txtUrina.getText().equals(" ")) {
            txtUrina.setText("");
        }
    }//GEN-LAST:event_txtUrinaFocusGained

    private void txtSemenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemenFocusGained
        if (txtSemen.getText().equals("0") || txtSemen.getText().equals(" ")) {
            txtSemen.setText("");
        }
    }//GEN-LAST:event_txtSemenFocusGained

    private void txtLeiteMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLeiteMaternoFocusGained
        if (txtLeiteMaterno.getText().equals("0") || txtLeiteMaterno.getText().equals(" ")) {
            txtLeiteMaterno.setText("");
        }
    }//GEN-LAST:event_txtLeiteMaternoFocusGained

    private void txtLiquorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLiquorFocusGained
        if (txtLiquor.getText().equals("0") || txtLiquor.getText().equals(" ")) {
            txtLiquor.setText("");
        }
    }//GEN-LAST:event_txtLiquorFocusGained

    private void txtPlacentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacentaFocusGained
        if (txtPlacenta.getText().equals("0") || txtPlacenta.getText().equals(" ")) {
            txtPlacenta.setText("");
        }
    }//GEN-LAST:event_txtPlacentaFocusGained

    private void txtCordaoUmbilicalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCordaoUmbilicalFocusGained
        if (txtCordaoUmbilical.getText().equals("0") || txtCordaoUmbilical.getText().equals(" ")) {
            txtCordaoUmbilical.setText("");
        }
    }//GEN-LAST:event_txtCordaoUmbilicalFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JComboBox<String> cmbAmostra1;
    private javax.swing.JComboBox<String> cmbAmostra2;
    private javax.swing.JComboBox<String> cmbAmostra3;
    private javax.swing.JComboBox<String> cmbAmostra4;
    private javax.swing.JComboBox<String> cmbFinalMae;
    private javax.swing.JComboBox<String> cmbFinalRN;
    private org.jdesktop.swingx.JXDatePicker dtColeta1;
    private org.jdesktop.swingx.JXDatePicker dtColeta2;
    private org.jdesktop.swingx.JXDatePicker dtColeta3;
    private org.jdesktop.swingx.JXDatePicker dtColeta4;
    private org.jdesktop.swingx.JXDatePicker dtColeta5;
    private org.jdesktop.swingx.JXDatePicker dtEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblContPalavras;
    private javax.swing.JLabel lblDtCol1;
    private javax.swing.JLabel lblDtCol2;
    private javax.swing.JLabel lblDtCol3;
    private javax.swing.JLabel lblDtCol4;
    private javax.swing.JLabel lblDtCol5;
    private javax.swing.JLabel lblDtEntrada;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNrCaso;
    private javax.swing.JTextPane txtAreaObs;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCordaoUmbilical;
    private javax.swing.JTextField txtLeiteMaterno;
    private javax.swing.JTextField txtLiquor;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JFormattedTextField txtNrCaso;
    private javax.swing.JTextField txtPlacenta;
    private javax.swing.JTextField txtPlasma;
    private javax.swing.JTextField txtSaliva;
    private javax.swing.JTextField txtSemen;
    private javax.swing.JTextField txtSoro;
    private javax.swing.JTextField txtUrina;
    // End of variables declaration//GEN-END:variables
}
