/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author Fabio
 */
public class NovoPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoPaciente
     */
    private static boolean podeProsseguir = false;
    private String campoComErroCPF = "";
    private String campoComErroNome = "";
    private String campoComErroNraso = "";
    
    public NovoPaciente() throws ParseException {
        initComponents();
        MaskFormatter maskNrCaso = new MaskFormatter("###/##"); 
        maskNrCaso.install(txtNrCaso);
        
        MaskFormatter maskCPF = new MaskFormatter("###.###.###-##"); 
        maskCPF.install(txtCPF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        dateColeta1 = new org.jdesktop.swingx.JXDatePicker();
        dateColeta2 = new org.jdesktop.swingx.JXDatePicker();
        dateColeta3 = new org.jdesktop.swingx.JXDatePicker();
        dateColeta4 = new org.jdesktop.swingx.JXDatePicker();
        dateColeta5 = new org.jdesktop.swingx.JXDatePicker();
        txtNrCaso = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        dateEntrada = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbAmostra1 = new javax.swing.JComboBox<>();
        cmbAmostra2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbAmostra3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbFinalMae = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbFinalRN = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        lblNrCaso = new javax.swing.JLabel();
        lblNrcasoCompleto = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Novo Paciente");

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Numero do Caso:");

        jLabel4.setText("Data da 1ª Coleta:");

        jLabel5.setText("Data da 2ª Coleta:");

        jLabel6.setText("Data da 3ª Coleta:");

        jLabel7.setText("Data da 4ª Coleta:");

        jLabel8.setText("Data da 5ª Coleta:");

        txtNomeCompleto.setText("Informe o Nome Completo");
        txtNomeCompleto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCompletoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeCompletoFocusLost(evt);
            }
        });
        txtNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompletoActionPerformed(evt);
            }
        });

        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });

        txtNrCaso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNrCasoFocusLost(evt);
            }
        });
        txtNrCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrCasoActionPerformed(evt);
            }
        });

        jLabel9.setText("Data da Entrada: ");

        jButton1.setText("Criar Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("1ª Amostra:");

        cmbAmostra1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbAmostra1.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbAmostra1.setName(""); // NOI18N
        cmbAmostra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmostra1ActionPerformed(evt);
            }
        });

        cmbAmostra2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbAmostra2.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbAmostra2.setName(""); // NOI18N
        cmbAmostra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmostra2ActionPerformed(evt);
            }
        });

        jLabel11.setText("2ª Amostra:");

        cmbAmostra3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbAmostra3.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbAmostra3.setName(""); // NOI18N
        cmbAmostra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmostra3ActionPerformed(evt);
            }
        });

        jLabel12.setText("3ª Amostra:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        jComboBox4.setMinimumSize(new java.awt.Dimension(90, 22));
        jComboBox4.setName(""); // NOI18N
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel13.setText("4ª Amostra:");

        cmbFinalMae.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbFinalMae.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbFinalMae.setName(""); // NOI18N
        cmbFinalMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFinalMaeActionPerformed(evt);
            }
        });

        jLabel14.setText("Final da Mãe:");

        cmbFinalRN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Negativo", "Positivo" }));
        cmbFinalRN.setMinimumSize(new java.awt.Dimension(90, 22));
        cmbFinalRN.setName(""); // NOI18N
        cmbFinalRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFinalRNActionPerformed(evt);
            }
        });

        jLabel15.setText("Final do RN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cmbAmostra1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cmbAmostra2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cmbAmostra3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cmbFinalMae, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cmbFinalRN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFinalRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFinalMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAmostra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAmostra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAmostra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resultados", jPanel1);

        lblNrCaso.setText("jLabel16");

        lblNrcasoCompleto.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNrCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateColeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateColeta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateColeta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateColeta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateColeta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeCompleto))))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNrcasoCompleto)
                            .addComponent(lblNrCaso))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNrCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(dateEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNrCaso)))
                    .addComponent(lblNrcasoCompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateColeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateColeta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateColeta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateColeta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateColeta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNrCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrCasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrCasoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbAmostra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmostra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmostra1ActionPerformed

    private void cmbAmostra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmostra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmostra2ActionPerformed

    private void cmbAmostra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmostra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmostra3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void cmbFinalMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFinalMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFinalMaeActionPerformed

    private void cmbFinalRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFinalRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFinalRNActionPerformed
    
    
    private void txtNrCasoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNrCasoFocusLost
        String nrCaso = txtNrCaso.getText();
        
        StringBuilder sb = new StringBuilder();
        
        try{
            for (int i = 0; i < 3; i++) {
                sb.append(nrCaso.charAt(i));
            }
            lblNrCaso.setText(sb.toString());
            lblNrcasoCompleto.setText(nrCaso.replace("/", ""));
        
            int contaNrCaso = Integer.parseInt(sb.toString());
        
            if (contaNrCaso > 500 || contaNrCaso <= 0) {
                JOptionPane.showMessageDialog(rootPane, "O numero do caso é maior que 500 ou menor ou igual a 0");
                txtNrCaso.setText("");
                podeProsseguir = false;
                campoComErroNome = "Informar o numero do caso corretamente!";
            }else if (txtNrCaso.getText().equals(null)) {
                JOptionPane.showMessageDialog(rootPane, "O numero do caso está em branco!");
                podeProsseguir = false;
                campoComErroNome = "Informar o numero do caso corretamente!";
            }else{
                podeProsseguir = true;
            }
           }catch(NumberFormatException nFE){
               JOptionPane.showMessageDialog(rootPane, "O formato do campo numero do caso, está incorreto! \n "
                       + "O formato para o campo numero do caso é, por exemplo: 012/34");
               podeProsseguir = false;
               campoComErroNome = "Informar o numero do caso corretamente!";
        }
        
        
        
    }//GEN-LAST:event_txtNrCasoFocusLost

    private void txtNomeCompletoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCompletoFocusGained
        if (txtNomeCompleto.getText().equals("Informe o Nome Completo")) {
            txtNomeCompleto.setText("");
        }
            
    }//GEN-LAST:event_txtNomeCompletoFocusGained

    private void txtNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompletoActionPerformed

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
        try{
          
        }catch(NumberFormatException nFE){
            JOptionPane.showMessageDialog(rootPane, "O formato do campo CPF, está incorreto! \n "
                       + "O formato para o CPF é, por exemplo: 123.456.789-01");
        }
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtNomeCompletoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCompletoFocusLost
        if (txtNomeCompleto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo nome completo está em branco!");
            campoComErroNome = "Informar o nome competo!";
            podeProsseguir = false;
        }else{
            podeProsseguir = true;
        }
    }//GEN-LAST:event_txtNomeCompletoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAmostra1;
    private javax.swing.JComboBox<String> cmbAmostra2;
    private javax.swing.JComboBox<String> cmbAmostra3;
    private javax.swing.JComboBox<String> cmbFinalMae;
    private javax.swing.JComboBox<String> cmbFinalRN;
    private org.jdesktop.swingx.JXDatePicker dateColeta1;
    private org.jdesktop.swingx.JXDatePicker dateColeta2;
    private org.jdesktop.swingx.JXDatePicker dateColeta3;
    private org.jdesktop.swingx.JXDatePicker dateColeta4;
    private org.jdesktop.swingx.JXDatePicker dateColeta5;
    private org.jdesktop.swingx.JXDatePicker dateEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNrCaso;
    private javax.swing.JLabel lblNrcasoCompleto;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JFormattedTextField txtNrCaso;
    // End of variables declaration//GEN-END:variables
}
