/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozikavirus;

import java.util.logging.Level;
import java.util.logging.Logger;
import telas.AlterarAmostras;
import telas.BuscarPaciente;
import telas.NovoPaciente;

/**
 *
 * @author Fabio
 */
public class TelaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemSair = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuItemNovoPaciente = new javax.swing.JMenuItem();
        mnuItemBuscarPaciente = new javax.swing.JMenuItem();
        mnuItemEditarPaciente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1028, 760));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        mnuItemSair.setText("Sair");
        mnuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Paciente");

        mnuItemNovoPaciente.setText("Novo Paciente");
        mnuItemNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNovoPacienteActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemNovoPaciente);

        mnuItemBuscarPaciente.setText("Buscar Paciente");
        mnuItemBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBuscarPacienteActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemBuscarPaciente);

        mnuItemEditarPaciente.setText("Editar Paciente");
        mnuItemEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEditarPacienteActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemEditarPaciente);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Sobre");

        jMenu3.setText("jMenu3");
        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("jMenu5");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void mnuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItemSairActionPerformed

    private void mnuItemNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNovoPacienteActionPerformed
        NovoPaciente novoPaciente;
        try {
            novoPaciente = new NovoPaciente();
            novoPaciente.setLocation((desktop.getWidth()/2) - (novoPaciente.getWidth()/2), (desktop.getHeight()/2) - (novoPaciente.getHeight()/2));
            desktop.add(novoPaciente);
            novoPaciente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error Message: " + ex.getMessage());
            System.out.println("Cause: " + ex.getCause());
            System.out.println("Stack Trace: " + ex.getStackTrace());
        }
        
    }//GEN-LAST:event_mnuItemNovoPacienteActionPerformed

    private void mnuItemBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBuscarPacienteActionPerformed
        BuscarPaciente buscarPaciente;
        try{            
            buscarPaciente = new BuscarPaciente();
            buscarPaciente.setLocation((desktop.getWidth()/2) - (buscarPaciente.getWidth()/2), (desktop.getHeight()/2) - (buscarPaciente.getHeight()/2));
            desktop.add(buscarPaciente);
            buscarPaciente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error Message: " + ex.getMessage());
            System.out.println("Cause: " + ex.getCause());
            System.out.println("Stack Trace: " + ex.getStackTrace());
        }
    }//GEN-LAST:event_mnuItemBuscarPacienteActionPerformed

    private void mnuItemEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEditarPacienteActionPerformed
        BuscarPaciente buscarPaciente;
        try{            
            buscarPaciente = new BuscarPaciente();
            buscarPaciente.setLocation((desktop.getWidth()/2) - (buscarPaciente.getWidth()/2), (desktop.getHeight()/2) - (buscarPaciente.getHeight()/2));
            desktop.add(buscarPaciente);
            buscarPaciente.setVisible(true);
            buscarPaciente.setName("TelaBuscar");
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error Message: " + ex.getMessage());
            System.out.println("Cause: " + ex.getCause());
            System.out.println("Stack Trace: " + ex.getStackTrace());
        }
    }//GEN-LAST:event_mnuItemEditarPacienteActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AlterarAmostras alterarAmostras;
        try{            
            alterarAmostras = new AlterarAmostras();
            alterarAmostras.setLocation((desktop.getWidth()/2) - (alterarAmostras.getWidth()/2), (desktop.getHeight()/2) - (alterarAmostras.getHeight()/2));
            desktop.add(alterarAmostras);
            alterarAmostras.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error Message: " + ex.getMessage());
            System.out.println("Cause: " + ex.getCause());
            System.out.println("Stack Trace: " + ex.getStackTrace());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuItemBuscarPaciente;
    private javax.swing.JMenuItem mnuItemEditarPaciente;
    private javax.swing.JMenuItem mnuItemNovoPaciente;
    private javax.swing.JMenuItem mnuItemSair;
    // End of variables declaration//GEN-END:variables
}
